// Inlines the compiled kernel as base64, so the browser build and the Node
// scripts load it the same way and nobody needs clang to build the site.
import { readFileSync, writeFileSync } from "node:fs";
const wasm = readFileSync(new URL("./dot.wasm", import.meta.url));
writeFileSync(
  new URL("../src/search/kernel-wasm.ts", import.meta.url),
  `// Generated by kernel/embed.mjs from kernel/dot.c (${wasm.length} bytes). Do not edit.\nexport default "${wasm.toString("base64")}";\n`,
);
console.log(`kernel: ${wasm.length} bytes`);
